version: "3.8"

services:
  learn-laravel:
    image: learn-laravel
    container_name: learn-laravel
    build:
      context: ./docker/laravel
      dockerfile: Dockerfile
    volumes:
      - ./learn-laravel:/var/www/html
      - ./docker/laravel/php.ini-production:/usr/local/etc/php/conf.d/php.ini
    networks:
      - learn-laravel-network
    env_file: ./docker/laravel/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - learn-laravel-mysql
  learn-laravel-nginx:
    image: learn-laravel-nginx
    container_name: learn-laravel-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - learn-laravel-network
    env_file: ./docker/nginx/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - learn-laravel
  learn-laravel-mysql:
    image: learn-laravel-mysql
    container_name: learn-laravel-mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    volumes:
      - ./var/mysql:/var/lib/mysql:cached
      - ./docker/mysql/my.cnf:/etc/my.cnf
    networks:
      - learn-laravel-network
    env_file: ./docker/mysql/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  learn-laravel-network:
    name: learn-laravel-network
    driver: bridge
