version: "3.8"

services:

  learn-laravel:
    image: learn-laravel
    container_name: learn-laravel
    build:
      context: ./docker/laravel
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: learn-laravel-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./learn-laravel
        target: /var/www/html
      - type: bind
        source: ./docker/laravel/php.ini-production
        target: /usr/local/etc/php/conf.d/php.ini
      # Override `/usr/local/etc/php-fpm.d/zz-docker.conf` settings in container.
      # See: https://github.com/docker-library/php/issues/241
      - type: bind
        source: ./docker/laravel/zzz-docker-override.conf
        target: /usr/local/etc/php-fpm.d/zzz-docker-override.conf
    networks:
      - learn-laravel-network
    env_file: ./docker/laravel/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - learn-laravel-mysql

  learn-laravel-nginx:
    image: learn-laravel-nginx
    container_name: learn-laravel-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: learn-laravel-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./docker/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./docker/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    networks:
      - learn-laravel-network
    env_file: ./docker/nginx/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - learn-laravel

  learn-laravel-mysql:
    image: learn-laravel-mysql
    container_name: learn-laravel-mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    volumes:
      - ./var/mysql:/var/lib/mysql:cached
      - type: bind
        source: ./docker/mysql/my.cnf
        target: /etc/my.cnf
    networks:
      - learn-laravel-network
    env_file: ./docker/mysql/.env
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  learn-laravel-network:
    name: learn-laravel-network
    driver: bridge

volumes:
  # For sharing php-fpm socket.
  learn-laravel-fpm-socket:
